version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
  build:
    commands:
      - pip install pip==19.2.3
      - pip install pipenv --user
      - pipenv install awscli aws-sam-cli
      - pipenv run sam package --template-file template.yml --s3-bucket kususambuildrepo --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml	