version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kusu-sam-reborn"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2owaqj4mog0k"
s3_prefix = "kusu-sam-reborn"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

